travis:
  secure:
    BINSTAR_TOKEN: OBcgzffor9bNg/Uw9KkOM6GYCJApsHXSdKP+W+qq83vF7w84lzQInzjUsmFN1TsShyiGbviUXeGohzOF2OSxmUoUMj0oyyFZ7KQffEpk8/sThmWetWFhDePol4awnV5pft4BS5GQoyxN2dkt6ItIPDymCs6Yh/eWEtZKB+X31C3yWUGNmSGltILhSnGpJryMKHPOhHQvp3coJcIOwPdvf+r0L08EQCxDGD+C9BBtRombErlAA/2Uaf67JImgOjTs61HStvNchQbBpyVfPKnGvcUc1+OaThnOYNPwgqSRRnHKT6zdo3ume/gwQSd0Fi5E65AIlw4ST3MPHwyiU4EoBv1Zn2uy6zBgMF+I0oY9OpwUcuQxBdIo66UV5iz+pkmknt6lb/MoWZXz2tf2KQDzSHuevfhLGePD3tXLtoiS2bInNLmNFTy3lYh2cAVJTepAm0KHwU/9rgmw2WI6f8k56DURlhUkyh5UyFbMyIg5QZvpLBpzXL4DiRiTUwTPfRopepDcXUAjgxKPa5eP70rv9BADvcFPWcDV3mBply86+nkl0mWKnoGOSxmG64xXTtKV057V7tPhozHkjGhiJQaJ7shXNNqS7rq20MoiYgrmHCNOb7TG3LlcExfVE+cC86HRS1ZGI6WGdbcEvxdALs79z6wlUHmCRCDMcAlZn8GBGvY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
