travis:
  secure:
    BINSTAR_TOKEN: F88Z6VGdiwvlKA/DxWIO3qrJnsYuGYi5/PyifEuEH8tj7b8riaaa/qOQ8yWSA/8J13scZZNxVi3C7rR2THB4J1ZKTFnpONRughAuNFr3CMTk6B2BAYF4F0G9+TF/5XCBW/86CLHnl0P9lQKFyXbyOntA239aC9iKdo1bzA9FBbgqgi+s0vPQR034WnPONkRgcqZBJ90tzgmMSM+nWAQZrtNTDQuuhiFg6Kpp3gmihO4IGydQKeWjkX86EkwksoF/2/2e+wwM7wFBRo9PfKMLUXs9YshSzTD2kwhuNORbNbgnLg3N3vBS0IUCEocfzjVrij8leR+4EAfLwdoKU4ijha+xNmqlVo6dMBnigZnntCvxEF4dfuvmcBYzuyvoL+izCs5zpJ/P+MkZRCXKm/SLcDC2eEE99w1GLouLQkBFWGeXiobegHe1Hr8bfy4os9KRILIyo30EFlvwneiBqdRc6z9hOLHxzNDlfldhuv13yfULukQwB7Y9IXvW9P10KLUTgWipTQEc7QNsurdk9tyvE3dZMa6IHFxNGssoXb+sYqxPsjKMqiJc+MOBWAWU5wvkTv80nl7j8WsGo3cGvq5IdSEvaLzNsB7VwZp+kwv51Z6DbQ55YL2qcNLT/WgWQGNI46/tINpiGagb4fV61oRqDsHoCnA/kZNaTZuOzj17rrA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
